### PR TITLE
Adding keyword 'token' in the list of sensitive keywords

### PR DESCRIPTION
**Pull request by akshath-karanam**
It is imperative that tokens be hidden or represented by '*' across any of the configuration page and not by their actual values. This can be achieved by adding the keyword 'token' to the list of sensitive keywords. Doing so ensures that any key with 'token' in it is hidden / represented by astrixs.

Furthermore, this PR also adds to the tests, to validate that keys with 'token' are being hidden.

### CODE REVIEW

**Review by ytanida — APPROVED** [review]
LGTM

**Comment by bsankararao** [comment]
@akshath-karanam @ytanida I see that these changes  haven't been merged yet.

**Comment by aks-cmu** [comment]
@ytanida could you let me know what the plan is regarding getting this merged and making a new release?

**Review by rpayami — APPROVED** [review]

**Comment by yoikawa** [comment]
can't merge unsigned commit.  merged #53 and closing this PR

**Pull request closed without merging**
